### ISSUE TITLE
SkellettProxy - GetMaxPlayers - Critical Error - NullPointerExeption

### ISSUE THREAD

**Issue by SafeCoding** [TheLimeGlass/Skellett#44] opened 2017-06-29 14:05 UTC
**Server Information:**
  - Server OS: Linux Debian 8
  - Java Version: 1.8
  - Minecraft Version: 1.8.8
  - Server Software: Spigot 1.8.8
  - Spigot Version Code: git-Spigot-21fe-707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Skript Information:**
  - Skript Version: 2.2-Mineplex-Core-Patch
  - Skellett Version: 1.9.4

**Error Information:**
  - Type: NullPointerExeption
  
  - Skript Code:
   `set {_playermax} to max players of bungeecord server "reallife"`

  - Optional Information:
All other features work perfect (getPlayersCurrentOnline, sendMessageToAllBungeeCordPlayers, sendMessageToBungeeCordPlayer, sendPlayerToServer, etc). Only this function is buggy!

  - Error Code:
  `[09:49:06] [Server thread/INFO]: [0;30;1m[[0;32;1mSkellett[0;30;1m] [0;33;1mConnected to SkellettProxy![m
[09:49:10] [Server thread/INFO]: [0;30;1m[[0;32;1mSkellett[0;30;1m] [0;33;1m[0;31;1mIncorrect SkellettProxy details, No socket found or was denied access. For socket at 127.0.0.1:15000[m
[09:49:10] [Server thread/ERROR]: [Skript] If you're 100% sure your details are correct, this can be caused because some server's want a number host rather than localhost. Try inserting 0.0.0.0 or 127.0.0.1 instead of localhost. Error: 
[09:49:10] [Server thread/INFO]: [0;30;1m[[0;32;1mSkellett[0;30;1m] [0;33;1m[0;31;1mAttempting to reconnect and fix myself...[m
[09:49:10] [Server thread/ERROR]: #!#! 
[09:49:10] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[09:49:10] [Server thread/ERROR]: #!#! 
[09:49:10] [Server thread/ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[09:49:10] [Server thread/ERROR]: #!#! If you're a server admin however please go to http://dev.bukkit.org/server-mods/skript/tickets/
[09:49:10] [Server thread/ERROR]: #!#! and check whether this error has already been reported.
[09:49:10] [Server thread/ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it,
[09:49:10] [Server thread/ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[09:49:10] [Server thread/ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[09:49:10] [Server thread/ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[09:49:10] [Server thread/ERROR]: #!#! 
[09:49:10] [Server thread/ERROR]: #!#! Stack trace:
[09:49:10] [Server thread/ERROR]: #!#! java.lang.NullPointerException
[09:49:10] [Server thread/ERROR]: #!#!     at com.gmail.thelimeglass.Sockets.stop(Sockets.java:135)
[09:49:10] [Server thread/ERROR]: #!#!     at com.gmail.thelimeglass.Sockets.send(Sockets.java:105)
[09:49:10] [Server thread/ERROR]: #!#!     at com.gmail.thelimeglass.SkellettProxy.ExprBungeeMaxPlayersServer.get(ExprBungeeMaxPlayersServer.java:51)
[09:49:10] [Server thread/ERROR]: #!#!     at com.gmail.thelimeglass.SkellettProxy.ExprBungeeMaxPlayersServer.get(ExprBungeeMaxPlayersServer.java:1)
[09:49:10] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:103)
[09:49:10] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:270)
[09:49:10] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:54)
[09:49:10] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:63)
[09:49:10] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:91)
[09:49:10] [Server thread/ERROR]: #!#!     at com.pie.tlatoani.Throwable.ScopeTry.go(ScopeTry.java:26)
[09:49:10] [Server thread/ERROR]: #!#!     at com.pie.tlatoani.Util.CustomScope.check(CustomScope.java:213)
[09:49:10] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Condition.run(Condition.java:58)
[09:49:10] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Conditional.walk(Conditional.java:53)
[09:49:10] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:91)
[09:49:10] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.Delay$1.run(Delay.java:84)
[09:49:10] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[09:49:10] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[09:49:10] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
[09:49:10] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[09:49:10] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[09:49:10] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[09:49:10] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[09:49:10] [Server thread/ERROR]: #!#! 
[09:49:10] [Server thread/ERROR]: #!#! Version Information:
[09:49:10] [Server thread/ERROR]: #!#!   Skript: 2.2-Mineplex-Core-Patch
[09:49:10] [Server thread/ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[09:49:10] [Server thread/ERROR]: #!#!   Minecraft: 1.8.8
[09:49:10] [Server thread/ERROR]: #!#!   Java: 1.8.0_131 (Java HotSpot(TM) 64-Bit Server VM 25.131-b11)
[09:49:10] [Server thread/ERROR]: #!#!   OS: Linux amd64 2.6.32-042stab112.15
[09:49:10] [Server thread/ERROR]: #!#! 
[09:49:10] [Server thread/ERROR]: #!#! Running CraftBukkit: false
[09:49:10] [Server thread/ERROR]: #!#! 
[09:49:10] [Server thread/ERROR]: #!#! Current node: null
[09:49:10] [Server thread/ERROR]: #!#! Current item: set {_playermax}(as java.lang.Object) to [the] max[imum] [amount] [of] players for (skellett[ ][(cord|proxy)]|bungee[ ][cord]) server %string%
[09:49:10] [Server thread/ERROR]: #!#! 
[09:49:10] [Server thread/ERROR]: #!#! Thread: Server thread
[09:49:10] [Server thread/ERROR]: #!#! 
[09:49:10] [Server thread/ERROR]: #!#! End of Error.
[09:49:10] [Server thread/ERROR]: #!#! `

**Comment by TheLimeGlass** [comment] 2017-07-12 11:26
Can't reproduce. I will try again some time to figure out what the error is. It seems SkellettProxy already knows of this error and fixed itself.

**Comment by TheLimeGlass** [comment] 2018-01-09 00:03
Fixed with the latest Skungee. Try it out. its a remake of SkellettProxy https://www.spigotmc.org/resources/skript-java-addon-skungee-bungeecord-addon-for-skript.35636/

**Closed by TheLimeGlass** 2018-01-09 00:03 UTC
Labels: bug, invalid, investigating
